### ISSUE TITLE
GeoPackage.getFeatureDao() fails if geopackage uses RTree and file is not writable

### ISSUE THREAD

**Issue by Remboooo** [ngageoint/geopackage-java#58]
#### Version Information:

  * GeoPackage Java Version: 6.3.0
  * GeoPackage Java Source: Maven Central
  * IDE Name & Version: IntelliJ IDEA 2021.02 CE
  * Maven Version: none, using gradle 6.8.2
  * Java Version: OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
  * Platform & OS: x64, Windows 10 Pro
  * Other Relevant Libraries: org.xerial.sqlite-jdbc 3.36.0.3

#### Expected Results:

  * What did you expect to happen?

When reading a geopackage from a read-only file, as long as performing read operations, no errors should occur

#### Observed Results:

  * What happened instead?
When calling `GeoPackage.getFeatureDao(String)`, the following exception is produced: `java.sql.SQLException: error creating function`. The root cause is that `RTreeIndexCoreExtension` tries to create some functions, but in the sqlite package the JNI function `create_function` produces error code 5 (`SQLITE_BUSY`, meaning the database file is locked).

  * How often does this occur?
Every time.

#### Output:

  * Any logs, errors, or output messages?
```
java.sql.SQLException: error creating function
	at org.sqlite.Function.create(Function.java:124) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.Function.create(Function.java:92) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.Function.create(Function.java:80) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at mil.nga.geopackage.extension.rtree.RTreeIndexExtension.createFunction(RTreeIndexExtension.java:185) ~[geopackage-6.3.0.jar:na]
	at mil.nga.geopackage.extension.rtree.RTreeIndexExtension.createMinYFunction(RTreeIndexExtension.java:123) ~[geopackage-6.3.0.jar:na]
	at mil.nga.geopackage.extension.rtree.RTreeIndexCoreExtension.createAllFunctions(RTreeIndexCoreExtension.java:441) ~[geopackage-core-6.3.0.jar:na]
	at mil.nga.geopackage.extension.rtree.RTreeIndexCoreExtension.createFunctions(RTreeIndexCoreExtension.java:348) ~[geopackage-core-6.3.0.jar:na]
	at mil.nga.geopackage.extension.rtree.RTreeIndexCoreExtension.createFunctions(RTreeIndexCoreExtension.java:330) ~[geopackage-core-6.3.0.jar:na]
	at mil.nga.geopackage.GeoPackageImpl.getFeatureDao(GeoPackageImpl.java:123) ~[geopackage-6.3.0.jar:na]
	at mil.nga.geopackage.GeoPackageImpl.getFeatureDao(GeoPackageImpl.java:196) ~[geopackage-6.3.0.jar:na]
```

#### Steps to Reproduce:

  1. Create/get a gpkg file with RTree extensions
  2. Open the file in another program on an OS that disallows writing to a file when that file is also opened by another process
  3. `GeoPackageManager.open()` said file
  4. `geoPackage.getFeatureDao("some_table")`

#### Relevant Code:

In `GeoPackageImpl.getFeatureDao(GeometryColumns)` (`GeoPackageImpl.java:121`):
```
		if (writable) {
			RTreeIndexExtension rtree = new RTreeIndexExtension(this);
			rtree.createFunctions(featureTable);
		}
```
But, there is no way to create a `GeoPackage` instance that has `writable == false` because it is hard-coded as the last argument of the `super()` call in the constructor in `GeoPackageImpl.java:73`:
```
		super(name, path, database, true);
```
As the variable `writable` is `final`, there is no way around this.

#### Test Files:

https://service.pdok.nl/bzk/brogmwvolledigeset/atom/v2_1/downloads/brogmwvolledigeset.zip

#### Additional Information:

I have verified that fudging `writable = false` using reflection eliminates the exception and everything works as it should:
```
var writable = GeoPackageCoreImpl.class.getDeclaredField("writable");
writable.setAccessible(true);
writable.set(geoPackage, false);
var featureDao = geoPackage.getFeatureDao("my_table"); // now works even if file is opened elsewhere
```

**Comment by bosborn** [comment]
[These changes](https://github.com/ngageoint/geopackage-java/commit/554987ac3ca005c13a246db81d9091248708607c) will allow you to provide the writable flag.  Going to keep the default value as true for cases when access cannot be determined ([via Files.isWritable](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#isWritable(java.nio.file.Path))).
